### ISSUE TITLE
High download latency

### ISSUE THREAD

**Issue by s3a6m9** [morrownr/rtl8852bu#24]
Running this driver on arch linux kernel 6.8.1-arch1-1 yields a higher download latency than it does on the same machine using windows (~30ms, 300-500ms respectively). The download/upload rates are around the same.

**Comment by morrownr** [comment]
Are you checking this with ping?

**Comment by s3a6m9** [comment]
No, I ran tests on speedtest by ookla. The dongle I am using is a BrosTrend AX1800 (AX4).

**Comment by s3a6m9** [comment]
It could be a browser issue, as I was testing on a Chrome binary from AUR. Using ping and testing multiplayer games, it actually maintains a lower latency than my other wired connection. However, when testing the 5G on the dongle, it goes up to around 200 ms or so every 5th ping. I used this driver to play games and other activities, and it worked fine on 2.4 GHz, so it may only be the 5G connections with the strange jitter. I'm able to confirm that it works well on Arch with kernel 6.8.1. Thanks for your help.

**Comment by morrownr** [comment]
@s3a6m9 

A lot of things can affect latency but I checked my notes over the last month and it seems almost all of the reports of latency on all of the drivers here have been by Arch users. Could it be something specific to Arch? It could be. I'll keep my eyes open, Oh, and all reports were with 5 GHz.

**Comment by ohquait** [comment]
it is the situation now ?
what will be changed in latency if you run under gdb ...
on last two weeks the major-distributions all effected by corrupted
xz and lzma libraries, however, the malicious code does not work if a debugger has been started beforehand and if no systemd is working with ssh  ...
so with running debugger you should become shorter latencies,
BUT
then you know also - system affected with the corruptions
....  not the driver-code here is the problem, just the loaded malicious codes from installed libraries
on your system
?
