### ISSUE TITLE
remove-driver.sh issue

### ISSUE THREAD

**Issue by cocuana** [morrownr/rtl8852bu#6]
https://github.com/morrownr/rtl8852bu/blob/117b322ad8a410ff3574530c53fe85c82b2b4b51/remove-driver.sh#L34
I think this is the issue...
The correct driver version that should go here it's not this DRV_VERSION="5.13.1", but DRV_VERSION="1.19.3"
Right?

Regards,

**Comment by morrownr** [comment]
Yes. Thank you for finding this. Patch merged.

I knew there would be issues as there were only 2 of us doing all of the work and testing. I appreciate you testing and reporting and hope that you have time to continue.

@morrownr

**Comment by cocuana** [comment]
Hi,
Anything I can help testing or improving, I'll be here:)
Regards,

**Comment by morrownr** [comment]
Thank you very much.
